# Generated by Django 5.1.4 on 2024-12-12 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='dodano',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
