# Generated by Django 5.1.4 on 2024-12-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0002_animals_dodano'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='status',
            field=models.CharField(choices=[('adoptowany', 'Adoptowany'), ('nieAdoptowany', 'NieAdoptowany')], default='nieAdoptowany', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='email@email.com', max_length=200),
        ),
    ]
