# Generated by Django 5.1.4 on 2025-01-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0003_animals_status_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='picture',
            field=models.CharField(default='brak', max_length=1000),
        ),
    ]
