# Generated by Django 5.1.4 on 2025-01-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0005_alter_animals_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
