# Generated by Django 5.1.4 on 2025-01-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0007_alter_animals_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='status',
            field=models.CharField(choices=[('adoptowany', 'Adoptowany'), ('nie-adoptowany', 'Nie-adoptowany')], default='Nie-adoptowany', max_length=20),
        ),
    ]
