# Generated by Django 4.2.17 on 2025-01-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0008_alter_animals_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.IntegerField(default='0', max_length=1),
        ),
    ]
