# Generated by Django 5.1.4 on 2025-01-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0011_alter_user_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
